/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: the process answers. Deliberately touches no dependency.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recordings */
        get: operations["list_recordings_v1_recordings_get"];
        put?: never;
        /** Start Recording */
        post: operations["start_recording_v1_recordings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recording */
        get: operations["get_recording_v1_recordings__recording_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recordings/{recording_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach Artifact */
        post: operations["attach_artifact_v1_recordings__recording_id__artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recordings/{recording_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Recording */
        post: operations["finish_recording_v1_recordings__recording_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/induct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Induce Skill
         * @description Two runs to one skill version. Runs synchronously: induction is pure
         *     computation over sealed recordings and takes milliseconds. The durable path
         *     through Temporal exists for callers that want a retryable handle.
         */
        post: operations["induce_skill_v1_skills_induct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill */
        get: operations["get_skill_v1_skills__skill_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills/{skill_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote Skill */
        post: operations["promote_skill_v1_skills__skill_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactKind
         * @enum {string}
         */
        ArtifactKind: "raw_events" | "video" | "screenshot" | "audio" | "transcript" | "payload";
        /** ArtifactModel */
        ArtifactModel: {
            /** Kind */
            kind: string;
            /** Uri */
            uri: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Frame Index */
            frame_index: number | null;
            /** Label */
            label: string | null;
        };
        /** AssertionModel */
        AssertionModel: {
            /** Kind */
            kind: string;
            /** Expected */
            expected: string;
            /** Pointer */
            pointer: string | null;
        };
        /** Body_attach_artifact_v1_recordings__recording_id__artifacts_post */
        Body_attach_artifact_v1_recordings__recording_id__artifacts_post: {
            kind: components["schemas"]["ArtifactKind"];
            /** File */
            file: string;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /**
         * Direction
         * @enum {string}
         */
        Direction: "inbound" | "outbound" | "internal";
        /** FinishRecordingRequest */
        FinishRecordingRequest: {
            /**
             * Abandon Reason
             * @description Present means abandon; absent means seal.
             */
            abandon_reason?: string | null;
        };
        /**
         * FrameSummary
         * @description Enough to render the timeline. The full frame is fetched per frame.
         */
        FrameSummary: {
            /** Index */
            index: number;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Action Kind */
            action_kind: string;
            /** Target */
            target: string | null;
            /** Request Count */
            request_count: number;
            /** Primary Request */
            primary_request: string | null;
            /** Error Count */
            error_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
        };
        /** InduceSkillRequest */
        InduceSkillRequest: {
            /** First Recording Id */
            first_recording_id: string;
            /** Second Recording Id */
            second_recording_id: string;
            /** Name */
            name?: string | null;
        };
        /** InductionResponse */
        InductionResponse: {
            /** Skill Id */
            skill_id: string;
            /** Version */
            version: number;
            /** Step Count */
            step_count: number;
            /** Input Parameter Count */
            input_parameter_count: number;
            /** Derived Parameter Count */
            derived_parameter_count: number;
        };
        /** NetworkPlanModel */
        NetworkPlanModel: {
            /** Method */
            method: string;
            /** Url */
            url: string;
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /** Body */
            body: string | null;
            /** Expected Status */
            expected_status: number | null;
            /** Replayable */
            replayable: boolean;
            /** Unreplayable Reason */
            unreplayable_reason: string | null;
            /** Required Credentials */
            required_credentials: string[];
        };
        /** ObjectiveKeyModel */
        ObjectiveKeyModel: {
            /** Objective Type */
            objective_type: string;
            /** Target System */
            target_system: string;
            /** Entity Type */
            entity_type: string;
            /** Facility */
            facility: string;
            direction: components["schemas"]["Direction"];
        };
        /** ParameterModel */
        ParameterModel: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            /** Observed Values */
            observed_values: string[];
            /** Source Step Index */
            source_step_index: number | null;
        };
        /** PromoteRequest */
        PromoteRequest: {
            /** Version */
            version: number;
            /** To */
            to: string;
        };
        /** RecordingDetail */
        RecordingDetail: {
            /** Id */
            id: string;
            objective_key: components["schemas"]["ObjectiveKeyModel"];
            /** Label */
            label: string | null;
            /** Status */
            status: string;
            /** Demonstrator */
            demonstrator: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Frame Count */
            frame_count: number;
            /** Has Narration */
            has_narration: boolean;
            /** Frames */
            frames: components["schemas"]["FrameSummary"][];
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactModel"][];
        };
        /** RecordingSummary */
        RecordingSummary: {
            /** Id */
            id: string;
            objective_key: components["schemas"]["ObjectiveKeyModel"];
            /** Label */
            label: string | null;
            /** Status */
            status: string;
            /** Demonstrator */
            demonstrator: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at: string | null;
            /** Frame Count */
            frame_count: number;
            /** Has Narration */
            has_narration: boolean;
        };
        /** SkillDetail */
        SkillDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            objective_key: components["schemas"]["ObjectiveKeyModel"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latest Version */
            latest_version: number;
            /** Latest Stage */
            latest_stage: string;
            /** Versions */
            versions: components["schemas"]["SkillVersionModel"][];
        };
        /** SkillSummary */
        SkillSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            objective_key: components["schemas"]["ObjectiveKeyModel"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latest Version */
            latest_version: number;
            /** Latest Stage */
            latest_stage: string;
        };
        /** SkillVersionModel */
        SkillVersionModel: {
            /** Version */
            version: number;
            /** Stage */
            stage: string;
            /**
             * Induced At
             * Format: date-time
             */
            induced_at: string;
            /** Induced By */
            induced_by: string;
            /** Recording Ids */
            recording_ids: string[];
            /** Provenance Note */
            provenance_note: string;
            /** Steps */
            steps: components["schemas"]["StepModel"][];
            /** Parameters */
            parameters: components["schemas"]["ParameterModel"][];
        };
        /** StartRecordingRequest */
        StartRecordingRequest: {
            objective_key: components["schemas"]["ObjectiveKeyModel"];
            /** Start Url */
            start_url?: string | null;
            /** Label */
            label?: string | null;
        };
        /** StartRecordingResponse */
        StartRecordingResponse: {
            /** Recording Id */
            recording_id: string;
            /** Live View Url */
            live_view_url: string;
        };
        /** StepModel */
        StepModel: {
            /** Index */
            index: number;
            /** Intent */
            intent: string;
            /** Requires Human */
            requires_human: boolean;
            network_plan: components["schemas"]["NetworkPlanModel"] | null;
            ui_plan: components["schemas"]["UiPlanModel"] | null;
            /** Assertions */
            assertions: components["schemas"]["AssertionModel"][];
        };
        /** UiPlanModel */
        UiPlanModel: {
            /** Action */
            action: string;
            /** Target */
            target: string | null;
            /** Target Path */
            target_path: string | null;
            /** Value */
            value: string | null;
            /** Wait For */
            wait_for: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_recordings_v1_recordings_get: {
        parameters: {
            query?: {
                objective_type?: string | null;
                target_system?: string | null;
                entity_type?: string | null;
                facility?: string | null;
                direction?: components["schemas"]["Direction"] | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Tenant-Id"?: string;
                "X-Principal-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_recording_v1_recordings_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-Principal-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRecordingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRecordingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_v1_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-Principal-Id"?: string;
            };
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_artifact_v1_recordings__recording_id__artifacts_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-Principal-Id"?: string;
            };
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_attach_artifact_v1_recordings__recording_id__artifacts_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_recording_v1_recordings__recording_id__finish_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-Principal-Id"?: string;
            };
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishRecordingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    induce_skill_v1_skills_induct_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-Principal-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InduceSkillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InductionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_v1_skills_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-Tenant-Id"?: string;
                "X-Principal-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_v1_skills__skill_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-Principal-Id"?: string;
            };
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_skill_v1_skills__skill_id__promote_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string;
                "X-Principal-Id"?: string;
            };
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
