from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "frontend" / "src" / "app" / "brand.css"
TARGET = ROOT / "new-chrome-extension" / "src" / "brand.generated.css"

HEADER = """/* Generated by `make tokens` from frontend/src/app/brand.css. Do not edit.
 *
 * The extension has no build step and does not want one; this is a copy, and
 * `tokens.test.mjs` is what notices when it is out of date. */
"""


def rendered() -> str:
    return HEADER + "\n" + SOURCE.read_text(encoding="utf-8")


def main() -> int:
    want = rendered()
    if TARGET.exists() and TARGET.read_text(encoding="utf-8") == want:
        print(f"{TARGET.relative_to(ROOT)} is current")
        return 0
    TARGET.write_text(want, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
