from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parents[2]
TARGET = HERE / "new-chrome-extension" / "src" / "background" / "deployment.generated.js"

TEMPLATE = """// GENERATED by `make gen-deployment` from backend/scripts/write_deployment.py.
// Do not edit this file directly -- regenerate it.
//
// Which deployment this build of the extension belongs to. An operator pastes
// a credential and nothing else; these are not theirs to know. A build for a
// different deployment is this file, regenerated.

/** Where this extension's backend answers. The extension appends `/v1/...`. */
export const DEFAULT_API_URL = {api};

/** Where its console lives, for the link in the panel. Blank if there is none. */
export const DEFAULT_CONSOLE_URL = {console};
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api", required=True, help="e.g. http://10.11.9.25:8088/api")
    parser.add_argument("--console", default="", help="e.g. http://10.11.9.25:8088")
    args = parser.parse_args(argv)

    for name, value in (("--api", args.api), ("--console", args.console)):
        if value and not value.startswith(("http://", "https://")):
            print(f"{name} must be an absolute url, got {value!r}", file=sys.stderr)
            return 2

    TARGET.write_text(
        TEMPLATE.format(
            api=_js(args.api.rstrip("/")),
            console=_js(args.console.rstrip("/")),
        )
    )
    print(f"wrote {TARGET.relative_to(HERE)}")
    print(f"  api     {args.api.rstrip('/')}")
    print(f"  console {args.console.rstrip('/') or '(none)'}")
    return 0


def _js(value: str) -> str:
    return '"' + value.replace("\\\\", "\\\\\\\\").replace('"', '\\\\"') + '"'


if __name__ == "__main__":
    raise SystemExit(main())
