"""The one measured batch every rig test was built on. Copied from
`new_agent_arch/tests/fixtures.py` (which loads it from
`new-chrome-extension/fixtures/batch.json`); the constant is the same bytes.
"""

BATCH: dict[str, object] = {
    "batch_id": "bat_browsertest_418908ee_1",
    "device_id": "dev_browsertest",
    "started_at": "2026-08-31T08:40:04.587Z",
    "ended_at": "2026-08-31T08:40:04.787Z",
    "mode": "passive",
    "recording_id": None,
    "events": [
        {
            "kind": "page",
            "at": "2026-08-31T08:40:04.582Z",
            "page_kind": "navigated",
            "url": "http://127.0.0.1:63319/",
            "detail": None,
            "tab_id": 1766715008,
        },
        {
            "kind": "page",
            "at": "2026-08-31T08:40:04.584Z",
            "page_kind": "loaded",
            "url": "http://127.0.0.1:63319/",
            "detail": None,
            "tab_id": 1766715008,
        },
        {
            "kind": "gesture",
            "gesture": {
                "kind": "type",
                "target": {
                    "tag": "input",
                    "role": None,
                    "name": "Client Code",
                    "secret": False,
                    "text": None,
                    "testId": None,
                    "cssPath": "input#client",
                    "xpath": "/html/body[1]/form[1]/input[1]",
                    "bounds": {"x": 88.890625, "y": 79.875, "width": 153, "height": 21},
                    "attributes": {"id": "client", "name": "clientCode", "type": "text"},
                    "component": {
                        "framework": "extjs",
                        "xtype": "textfield",
                        "itemId": "clientCode",
                        "name": "clientCode",
                        "fieldLabel": "Client Code",
                        "text": None,
                        "query": "panel#clients textfield#clientCode",
                        "chain": ["panel#clients", "textfield#clientCode"],
                    },
                },
                "value": "ACME-4471",
                "secret": False,
                "modifiers": [],
                "at": 1788165604.612,
                "url": "http://127.0.0.1:63319/",
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
            "page_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "gesture",
            "gesture": {
                "kind": "select",
                "target": {
                    "tag": "select",
                    "role": None,
                    "name": "Dock",
                    "secret": False,
                    "text": "choose\nDock 3",
                    "testId": None,
                    "cssPath": "select#dock",
                    "xpath": "/html/body[1]/form[1]/select[1]",
                    "bounds": {"x": 506.890625, "y": 80.875, "width": 65, "height": 19},
                    "attributes": {"id": "dock", "name": "dock"},
                    "component": None,
                },
                "value": "D3",
                "secret": False,
                "modifiers": [],
                "at": 1788165604.661,
                "url": "http://127.0.0.1:63319/",
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
            "page_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "gesture",
            "gesture": {
                "kind": "upload",
                "target": {
                    "tag": "input",
                    "role": None,
                    "name": "Manifest",
                    "secret": False,
                    "text": None,
                    "testId": None,
                    "cssPath": "input#manifest",
                    "xpath": "/html/body[1]/form[1]/input[3]",
                    "bounds": {"x": 636.765625, "y": 79.875, "width": 253, "height": 21},
                    "attributes": {"id": "manifest", "name": "manifest", "type": "file"},
                    "component": None,
                },
                "value": "manifest.csv",
                "modifiers": [],
                "at": 1788165604.676,
                "url": "http://127.0.0.1:63319/",
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
            "page_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "gesture",
            "gesture": {
                "kind": "type",
                "target": {
                    "tag": "input",
                    "role": None,
                    "name": None,
                    "secret": True,
                    "text": None,
                    "testId": None,
                    "cssPath": "input#pw",
                    "xpath": "/html/body[1]/form[1]/input[2]",
                    "bounds": {"x": 311.234375, "y": 79.875, "width": 153, "height": 21},
                    "attributes": {"id": "pw", "name": "password", "type": "password"},
                    "component": None,
                },
                "value": None,
                "secret": True,
                "modifiers": [],
                "at": 1788165604.72,
                "url": "http://127.0.0.1:63319/",
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
            "page_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "gesture",
            "gesture": {
                "kind": "click",
                "target": {
                    "tag": "input",
                    "role": None,
                    "name": "Client Code",
                    "secret": False,
                    "text": None,
                    "testId": None,
                    "cssPath": "input#client",
                    "xpath": "/html/body[1]/form[1]/input[1]",
                    "bounds": {"x": 88.890625, "y": 79.875, "width": 153, "height": 21},
                    "attributes": {"id": "client", "name": "clientCode", "type": "text"},
                    "component": {
                        "framework": "extjs",
                        "xtype": "textfield",
                        "itemId": "clientCode",
                        "name": "clientCode",
                        "fieldLabel": "Client Code",
                        "text": None,
                        "query": "panel#clients textfield#clientCode",
                        "chain": ["panel#clients", "textfield#clientCode"],
                    },
                },
                "modifiers": [],
                "at": 1788165604.721,
                "url": "http://127.0.0.1:63319/",
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
            "page_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "gesture",
            "gesture": {
                "kind": "press",
                "target": {
                    "tag": "input",
                    "role": None,
                    "name": "Client Code",
                    "secret": False,
                    "text": None,
                    "testId": None,
                    "cssPath": "input#client",
                    "xpath": "/html/body[1]/form[1]/input[1]",
                    "bounds": {"x": 88.890625, "y": 79.875, "width": 153, "height": 21},
                    "attributes": {"id": "client", "name": "clientCode", "type": "text"},
                    "component": {
                        "framework": "extjs",
                        "xtype": "textfield",
                        "itemId": "clientCode",
                        "name": "clientCode",
                        "fieldLabel": "Client Code",
                        "text": None,
                        "query": "panel#clients textfield#clientCode",
                        "chain": ["panel#clients", "textfield#clientCode"],
                    },
                },
                "value": "Enter",
                "modifiers": [],
                "at": 1788165604.731,
                "url": "http://127.0.0.1:63319/",
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
            "page_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "gesture",
            "gesture": {
                "kind": "click",
                "target": {
                    "tag": "button",
                    "role": None,
                    "name": "Save",
                    "secret": False,
                    "text": "Save",
                    "testId": None,
                    "cssPath": "button#save",
                    "xpath": "/html/body[1]/form[1]/button[1]",
                    "bounds": {"x": 893.765625, "y": 79.875, "width": 46.390625, "height": 21},
                    "attributes": {"id": "save", "type": "button"},
                    "component": {
                        "framework": "extjs",
                        "xtype": "button",
                        "itemId": "saveButton",
                        "name": None,
                        "fieldLabel": None,
                        "text": "Save",
                        "query": "panel#clients button#saveButton",
                        "chain": ["panel#clients", "button#saveButton"],
                    },
                },
                "modifiers": [],
                "at": 1788165604.765,
                "url": "http://127.0.0.1:63319/",
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
            "page_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "request",
            "request": {
                "request_id": "req_808d0ef3_0",
                "method": "GET",
                "url": "http://127.0.0.1:63319/api/orders?facility=DC1",
                "resource_type": "fetch",
                "started_at": "2026-08-31T08:40:04.765Z",
                "request_headers": {},
                "request_body": None,
                "status": 200,
                "status_text": "OK",
                "response_headers": {
                    "access-control-allow-headers": "*",
                    "access-control-allow-origin": "*",
                    "content-length": "29",
                    "content-type": "application/json",
                    "date": "Mon, 31 Aug 2026 08:40:04 GMT",
                    "server": "BaseHTTP/0.6 Python/3.14.7",
                },
                "response_body": {
                    "text": '{"orders": [{"id": "ORD-1"}]}',
                    "size_bytes": 29,
                    "mime_type": "application/json",
                    "encoding": None,
                    "redacted_fields": [],
                },
                "redirect_chain": [],
                "duration_ms": 15,
                "from_cache": False,
                "failure_reason": None,
                "blocked_reason": None,
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "request",
            "request": {
                "request_id": "req_808d0ef3_1",
                "method": "POST",
                "url": "http://127.0.0.1:63319/api/orders",
                "resource_type": "fetch",
                "started_at": "2026-08-31T08:40:04.781Z",
                "request_headers": {"content-type": "application/json"},
                "request_body": {
                    "text": '{"clientCode":"ACME-4471","dock":"D3"}',
                    "size_bytes": 38,
                    "mime_type": "application/json",
                    "encoding": None,
                    "redacted_fields": [],
                },
                "status": 200,
                "status_text": "OK",
                "response_headers": {
                    "access-control-allow-headers": "*",
                    "access-control-allow-origin": "*",
                    "content-length": "12",
                    "content-type": "application/json",
                    "date": "Mon, 31 Aug 2026 08:40:04 GMT",
                    "server": "BaseHTTP/0.6 Python/3.14.7",
                },
                "response_body": {
                    "text": '{"ok": true}',
                    "size_bytes": 12,
                    "mime_type": "application/json",
                    "encoding": None,
                    "redacted_fields": [],
                },
                "redirect_chain": [],
                "duration_ms": 1,
                "from_cache": False,
                "failure_reason": None,
                "blocked_reason": None,
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "request",
            "request": {
                "request_id": "req_808d0ef3_2",
                "method": "GET",
                "url": "http://127.0.0.1:1/never",
                "resource_type": "fetch",
                "started_at": "2026-08-31T08:40:04.782Z",
                "request_headers": {},
                "request_body": None,
                "status": None,
                "status_text": None,
                "response_headers": {},
                "response_body": None,
                "redirect_chain": [],
                "duration_ms": 1,
                "from_cache": False,
                "failure_reason": "Failed to fetch",
                "blocked_reason": None,
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "request",
            "request": {
                "request_id": "req_808d0ef3_3",
                "method": "POST",
                "url": "http://127.0.0.1:63319/api/legacy",
                "resource_type": "xhr",
                "started_at": "2026-08-31T08:40:04.783Z",
                "request_headers": {"content-type": "application/x-www-form-urlencoded"},
                "request_body": {
                    "text": "clientCode=ACME-4471&dock=D3",
                    "size_bytes": 28,
                    "mime_type": "application/x-www-form-urlencoded",
                    "encoding": None,
                    "redacted_fields": [],
                },
                "status": 200,
                "status_text": "OK",
                "response_headers": {
                    "access-control-allow-headers": "*",
                    "access-control-allow-origin": "*",
                    "content-length": "12",
                    "content-type": "application/json",
                    "date": "Mon, 31 Aug 2026 08:40:04 GMT",
                    "server": "BaseHTTP/0.6 Python/3.14.7",
                },
                "response_body": {
                    "text": '{"ok": true}',
                    "size_bytes": 12,
                    "mime_type": "application/json",
                    "encoding": None,
                    "redacted_fields": [],
                },
                "redirect_chain": [],
                "duration_ms": 1,
                "from_cache": False,
                "failure_reason": None,
                "blocked_reason": None,
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
        },
        {
            "kind": "request",
            "request": {
                "request_id": "req_808d0ef3_4",
                "method": "GET",
                "url": "http://127.0.0.1:63319/api/stream",
                "resource_type": "fetch",
                "started_at": "2026-08-31T08:40:04.785Z",
                "request_headers": {},
                "request_body": None,
                "status": 200,
                "status_text": "OK",
                "response_headers": {
                    "content-type": "text/event-stream",
                    "date": "Mon, 31 Aug 2026 08:40:04 GMT",
                    "server": "BaseHTTP/0.6 Python/3.14.7",
                },
                "response_body": None,
                "redirect_chain": [],
                "duration_ms": 1,
                "from_cache": False,
                "failure_reason": None,
                "blocked_reason": None,
            },
            "tab_id": 1766715008,
            "frame_url": "http://127.0.0.1:63319/",
        },
    ],
}
