from __future__ import annotations

from collections.abc import Mapping
from datetime import timedelta
from typing import Protocol


class BlobStore(Protocol):
    async def put(self, key: str, data: bytes, *, content_type: str) -> str: ...

    async def presigned_url(self, key: str, *, expires_in: timedelta) -> str: ...

    async def presigned_url_for_uri(self, uri: str, *, expires_in: timedelta) -> str | None: ...

    async def read(self, uri: str) -> bytes: ...

    async def forget(self, uri: str) -> None: ...

    async def list_prefix(self, prefix: str) -> Mapping[str, int]: ...

    async def forget_prefix(self, prefix: str) -> int: ...
