// GENERATED by `make gen-recorder` from backend/src/sro/infrastructure/steel/sensitivity.py.
// Do not edit this file directly -- edit that one and regenerate.

// The redaction rules: which field names and which header names name a
// credential, and what a URL looks like with the credential-named query and
// fragment values taken out.
//
// `is_replayable` on the Python side answers SEMANTIC only, so an auth, CSRF
// or session value is never sent again by an executor -- storing one would be
// pure risk with no downstream use at all. They are dropped here, at the point
// of capture, rather than filtered later.
//
// Service-worker half: a module, because that worker has no window and no
// content script runs for a webNavigation event.

const SECRET_WORDS = new Set(["accesskey", "accesstoken", "apikey", "apisecret", "appsecret", "authkey", "authorization", "authtoken", "backupcode", "bearer", "clientsecret", "connectionstring", "consumerkey", "consumersecret", "cookie", "credential", "credentials", "csrf", "csrftoken", "cvv", "encryptionkey", "hotp", "htpasswd", "idrsa", "idtoken", "jsessionid", "jwt", "keystore", "logincode", "machinekey", "mfa", "oauthtoken", "onetimecode", "onetimepasscode", "otp", "pass", "passcode", "passphrase", "passwd", "password", "phpsessid", "pin", "privatekey", "privkey", "pwd", "recoverycode", "refreshtoken", "relaystate", "resettoken", "rsakey", "saml", "samlrequest", "samlresponse", "secret", "secretaccesskey", "secretanswer", "secretkey", "securityanswer", "securitycode", "sessionid", "sessionkey", "sessiontoken", "sshkey", "ssn", "sso", "token", "totp", "truststore", "verificationcode", "xapikey", "xauthtoken", "xsrf", "xsrftoken"]);
const SECRET_HEADERS = new Set(["api-key", "authentication", "authorization", "csrf-token", "proxy-authorization", "x-access-token", "x-api-key", "x-auth-token", "x-csrf-token", "x-csrftoken", "x-infor-token", "x-moca-session", "x-requested-with", "x-session-key", "x-xsrf-token"]);
const SECRET_HEADER_HINTS = ["auth", "cookie", "csrf", "jwt", "login", "sess", "sid", "sso", "token", "xsrf"];
// An OAuth authorization code is a credential; a warehouse `code` is not, and
// this tenant's traffic carries 138 field names ending in one. So `code` is
// matched exactly, and only beside another OAuth parameter -- which is what
// tells a callback hop from an ordinary call.
const OAUTH_COMPANIONS = new Set(["client_id", "code_challenge", "code_verifier", "grant_type", "id_token", "nonce", "redirect_uri", "response_type", "state"]);
const REDACTED = '«redacted»';

// `([A-Z]{2,})([A-Z][a-z])` and not `([A-Z]+)(...)`: the wider rule splits the
// lone N off `pickNPassAutoDropLocation` and leaves `Pass` bare, blanking a real
// warehouse field. Two-or-more needs three capitals in a row before it cuts, so
// `SAMLResponse` splits into saml/response and `NPass` stays whole. Measured
// over 3,270 real field, header and query names: it changes none of them.
const wordsOf = (text) =>
  (text || '')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]{2,})([A-Z][a-z])/g, '$1 $2')
    .split(/[^A-Za-z]+/)
    .filter(Boolean)
    .map((word) => word.toLowerCase());

const isSecretName = (name) => {
  const words = wordsOf(name);
  return words.some((word) => SECRET_WORDS.has(word)) || SECRET_WORDS.has(words.join(''));
};

// What a credential LOOKS like, whatever it is called. The words above are the
// secondary signal and have to be: a field name is whoever wrote the vendor's
// API's choice, an open vocabulary guessed at forever. A JWT is a JWT in any
// field, and a warehouse dock code is never a PEM block.
//
// Measured over 47,969 distinct real values from the acme store plus
// knowledge-base/http/exchanges: every pattern here matches zero of them. The
// case-blind pair is separate because `AKIA`, `AIza` and `eyJ` are
// case-SENSITIVE prefixes that a blind match would widen over the lowercase
// identifiers this traffic is full of.
const SECRET_SHAPE = new RegExp("(?<jwt>eyJ[A-Za-z0-9_-]{10,}(?:\\.[A-Za-z0-9_-]*){2,4})|(?<aws_key_id>(?:AKIA|ASIA|AIDA|AROA)[A-Z0-9]{16})|(?<github_token>gh[pousr]_[A-Za-z0-9]{36,})|(?<github_pat>github_pat_[A-Za-z0-9_]{20,})|(?<google_api_key>AIza[A-Za-z0-9_-]{35})|(?<slack_token>xox[abeprs]-[A-Za-z0-9-]{10,})|(?<private_key>-----BEGIN (?:[A-Z0-9]+ )*PRIVATE KEY-----(?:[\\s\\S]*?-----END (?:[A-Z0-9]+ )*PRIVATE KEY-----)?)", 'g');
const SECRET_SHAPE_ANY_CASE = new RegExp("(?<bearer>\\bbearer\\s+[A-Za-z0-9._~+/-]{20,})|(?<basic_auth>\\bbasic\\s+[A-Za-z0-9+/]{16,}={0,2})", 'gi');

// Every credential-shaped run replaced and every other byte left alone, so a
// string with nothing in it comes back identical -- which is what lets this
// run on a URL that must not be re-encoded.
const redactShapes = (text) =>
  typeof text === 'string' && text
    ? text.replace(SECRET_SHAPE, REDACTED).replace(SECRET_SHAPE_ANY_CASE, REDACTED)
    : text;

// Which shapes are in there, first seen first, so `redacted_fields` can say
// "this went because it looked like a JWT" rather than only that it went.
const shapesIn = (text) => {
  if (typeof text !== 'string' || !text) return [];
  const found = [];
  for (const matcher of [SECRET_SHAPE, SECRET_SHAPE_ANY_CASE]) {
    for (const match of text.matchAll(matcher)) {
      for (const [name, hit] of Object.entries(match.groups || {})) {
        if (hit !== undefined && !found.includes(name)) found.push(name);
      }
    }
  }
  return found;
};

const isSecretHeader = (name) => {
  const lowered = (name || '').toLowerCase().trim();
  // An HTTP/2 pseudo-header is the request line, not a header, and never a
  // credential. Checked first because `:authority` -- the host -- contains the
  // hint "auth", so the hints below redacted it. classify_header decides the
  // same case in the same order for the same reason.
  if (lowered.startsWith(':')) return false;
  if (SECRET_HEADERS.has(lowered)) return true;
  return SECRET_HEADER_HINTS.some((hint) => lowered.includes(hint));
};

// An `a=b&c=d` run with every credential-named value replaced.
//
// Rebuilt by hand rather than through `URLSearchParams.set` + `toString()`:
// that round-trip re-encodes every param, not just the touched one -- it
// collapses a repeated key to one, turns a literal space into `+`, and
// percent-encodes the marker itself, so grepping stored evidence for the same
// «redacted» every other redaction path writes finds nothing on a URL.
// Splicing leaves every untouched byte -- encoding, order, duplicates --
// exactly as the operator's browser sent it, and writes the marker as the
// same literal characters the body and header paths do. `split('&')` then
// `join('&')` is lossless, so a run with nothing to redact comes back
// byte-identical.
const redactPairs = (raw) => {
  const pairs = raw.split('&');
  const names = pairs.map((pair) => {
    const eq = pair.indexOf('=');
    const rawKey = eq === -1 ? pair : pair.slice(0, eq);
    try {
      return decodeURIComponent(rawKey.replace(/\+/g, ' ')).toLowerCase();
    } catch {
      return rawKey.toLowerCase();
    }
  });
  const oauth = names.some((name) => OAUTH_COMPANIONS.has(name));
  return pairs
    .map((pair, index) => {
      if (!pair) return pair;
      const eq = pair.indexOf('=');
      const rawKey = eq === -1 ? pair : pair.slice(0, eq);
      let key = rawKey;
      try {
        key = decodeURIComponent(rawKey.replace(/\+/g, ' '));
      } catch {
        // Not decodable: judged on the raw bytes instead of failing the whole
        // rebuild over one malformed pair.
      }
      if (!isSecretName(key) && !(oauth && names[index] === 'code')) return pair;
      return `${rawKey}=${REDACTED}`;
    })
    .join('&');
};

// `?token=...` and `?api_key=...` are as much a credential as the header form,
// and a URL is stored on every event there is: a page navigation, a request,
// and the frame a gesture happened in. Relative inputs are left alone rather
// than guessed at -- the service worker has no page to resolve them against.
//
// The fragment is judged by the same rule as the query: `#access_token=...`
// is exactly how an OAuth implicit flow hands a token back. The backend now
// redacts URLs too, at its own ingest boundary, because a rule that runs only
// in a browser is one a browser can be made not to run -- this copy is the
// first line, not the only one. A fragment with no `=` in it is a `#section`
// and is left alone rather than split into pairs it never had.
const redactUrl = (url) => {
  if (typeof url !== 'string' || !url) return url;
  // Validates the shape; the rebuild below works on the original string, not
  // on what `URL` would reserialize it to.
  try {
    void new URL(url);
  } catch {
    return url;
  }
  const hashStart = url.indexOf('#');
  const head = hashStart === -1 ? url : url.slice(0, hashStart);
  const fragment = hashStart === -1 ? '' : url.slice(hashStart + 1);
  const queryStart = head.indexOf('?');
  const redacted =
    queryStart === -1
      ? head
      : head.slice(0, queryStart + 1) + redactPairs(head.slice(queryStart + 1));
  // The shape pass runs over the whole rebuilt URL, not only the query: a
  // token can sit in a path segment, where no parameter name exists to judge
  // it by. It substitutes rather than replaces, so a URL with no credential in
  // it comes back byte-identical -- the property the hand-splicing above
  // exists to keep.
  return redactShapes(
    hashStart === -1
      ? redacted
      : `${redacted}#${fragment.includes('=') ? redactPairs(fragment) : fragment}`,
  );
};

export { isSecretName, isSecretHeader, redactUrl, redactShapes, shapesIn };
