from __future__ import annotations

import json
import re
from pathlib import Path

from sro.domain.recording.sensitivity import (
    _AUTH_HEADERS,
    _CSRF_HEADERS,
    _CSRF_HINTS,
    _SESSION_COOKIE_HINTS,
    OAUTH_COMPANIONS,
    SECRET_PHRASES,
    SECRET_SHAPES,
    SECRET_SHAPES_ANY_CASE,
    SECRET_TOKENS,
    SETTING_ROLES,
    TEXT_ROLES,
    TEXT_TAGS,
)
from sro.infrastructure.steel.capture import _recorder_script

_CONTENT = Path(__file__).resolve().parents[5] / "new-chrome-extension" / "src" / "content"
_BACKGROUND = Path(__file__).resolve().parents[5] / "new-chrome-extension" / "src" / "background"

RECORDER_OUT = _CONTENT / "recorder.generated.js"
SENSITIVITY_OUT = _CONTENT / "sensitivity.generated.js"
SENSITIVITY_MODULE_OUT = _CONTENT / "sensitivity.module.js"
SHAPE_OUT = _BACKGROUND / "shape.generated.js"
PAGE_CODE_OUT = _CONTENT.parent / "page" / "page-code.js"
_NAME_RULE_REGION = re.compile(
    r"^    // BEGIN generated secret-name rule\n.*?^    // END generated secret-name rule\n",
    re.M | re.S,
)

_HEADER = (
    "// GENERATED by `make gen-recorder` from backend/src/sro/infrastructure/steel/{source}.\n"
    "// Do not edit this file directly -- edit that one and regenerate.\n\n"
)


def recorder_source() -> str:
    return _HEADER.format(source="recorder.js") + _recorder_script()


_PURPOSE = """// The redaction rules: which field names and which header names name a
// credential, and what a URL looks like with the credential-named query and
// fragment values taken out.
//
// `is_replayable` on the Python side answers SEMANTIC only, so an auth, CSRF
// or session value is never sent again by an executor -- storing one would be
// pure risk with no downstream use at all. They are dropped here, at the point
// of capture, rather than filtered later.
"""


def _shape_source(shapes: tuple[tuple[str, str], ...]) -> str:
    return json.dumps("|".join(f"(?<{name}>{pattern})" for name, pattern in shapes))


def _name_rule() -> str:
    """The one secret-name rule in JavaScript, from sensitivity.py."""
    words = json.dumps(sorted(SECRET_TOKENS))
    phrases = json.dumps([list(phrase) for phrase in SECRET_PHRASES])
    return f"""const SECRET_WORDS = new Set({words});
// Multi-word credentials, read as the LAST words of one name, never across attributes.
const SECRET_PHRASES = {phrases};

// `([A-Z]{{2,}})([A-Z][a-z])` and not `([A-Z]+)(...)`: the wider rule splits the
// lone N off `pickNPassAutoDropLocation` and leaves `Pass` bare, blanking a real
// warehouse field. Two-or-more needs three capitals in a row before it cuts, so
// `SAMLResponse` splits into saml/response and `NPass` stays whole. Measured
// over 3,270 real field, header and query names: it changes none of them.
const wordsOf = (text) =>
  (text || '')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]{{2,}})([A-Z][a-z])/g, '$1 $2')
    .split(/[^A-Za-z]+/)
    .filter(Boolean)
    .map((word) => word.toLowerCase());

const isSecretName = (name) => {{
  const words = wordsOf(name);
  return (
    words.some((word) => SECRET_WORDS.has(word)) ||
    SECRET_WORDS.has(words.join('')) ||
    SECRET_PHRASES.some((phrase) =>
      phrase.every((word, i) => words[words.length - phrase.length + i] === word),
    )
  );
}};
"""


def _entry_rule() -> str:
    """The control-kind rule in JavaScript, from sensitivity.py (page code only)."""
    roles = [json.dumps(sorted(r)) for r in (SETTING_ROLES, TEXT_ROLES, TEXT_TAGS)]
    return f"""// A name judges only a control a person types text into; a checkbox, switch, select
// or combobox named "OTP enabled" holds a setting.
const SETTING_ROLES = new Set({roles[0]});
const TEXT_ROLES = new Set({roles[1]});
const TEXT_TAGS = new Set({roles[2]});
const isTextEntry = (role, tag, editable) => {{
  const typed = TEXT_TAGS.has((tag || '').toLowerCase());
  if (role === 'combobox' && typed) return true; // an <input role=combobox> is typed into
  if (SETTING_ROLES.has(role)) return false;
  if (TEXT_ROLES.has(role)) return true;
  return Boolean(editable) || (typed && role !== 'button');
}};
"""


def _rules() -> str:
    auth_headers = json.dumps(sorted(_AUTH_HEADERS | _CSRF_HEADERS))
    header_hints = json.dumps(sorted({*_CSRF_HINTS, *_SESSION_COOKIE_HINTS, "cookie"}))
    companions = json.dumps(sorted(OAUTH_COMPANIONS))
    shapes = _shape_source(SECRET_SHAPES)
    shapes_any_case = _shape_source(SECRET_SHAPES_ANY_CASE)
    return f"""{_name_rule()}
const SECRET_HEADERS = new Set({auth_headers});
const SECRET_HEADER_HINTS = {header_hints};
// An OAuth authorization code is a credential; a warehouse `code` is not, and
// this tenant's traffic carries 138 field names ending in one. So `code` is
// matched exactly, and only beside another OAuth parameter -- which is what
// tells a callback hop from an ordinary call.
const OAUTH_COMPANIONS = new Set({companions});
const REDACTED = '\u00abredacted\u00bb';

// What a credential LOOKS like, whatever it is called. The words above are the
// secondary signal and have to be: a field name is whoever wrote the vendor's
// API's choice, an open vocabulary guessed at forever. A JWT is a JWT in any
// field, and a warehouse dock code is never a PEM block.
//
// Measured over 47,969 distinct real values from the acme store plus
// knowledge-base/http/exchanges: every pattern here matches zero of them. The
// case-blind pair is separate because `AKIA`, `AIza` and `eyJ` are
// case-SENSITIVE prefixes that a blind match would widen over the lowercase
// identifiers this traffic is full of.
const SECRET_SHAPE = new RegExp({shapes}, 'g');
const SECRET_SHAPE_ANY_CASE = new RegExp({shapes_any_case}, 'gi');

// Every credential-shaped run replaced and every other byte left alone, so a
// string with nothing in it comes back identical -- which is what lets this
// run on a URL that must not be re-encoded.
const redactShapes = (text) =>
  typeof text === 'string' && text
    ? text.replace(SECRET_SHAPE, REDACTED).replace(SECRET_SHAPE_ANY_CASE, REDACTED)
    : text;

// Which shapes are in there, first seen first, so `redacted_fields` can say
// "this went because it looked like a JWT" rather than only that it went.
const shapesIn = (text) => {{
  if (typeof text !== 'string' || !text) return [];
  const found = [];
  for (const matcher of [SECRET_SHAPE, SECRET_SHAPE_ANY_CASE]) {{
    for (const match of text.matchAll(matcher)) {{
      for (const [name, hit] of Object.entries(match.groups || {{}})) {{
        if (hit !== undefined && !found.includes(name)) found.push(name);
      }}
    }}
  }}
  return found;
}};

const isSecretHeader = (name) => {{
  const lowered = (name || '').toLowerCase().trim();
  // An HTTP/2 pseudo-header is the request line, not a header, and never a
  // credential. Checked first because `:authority` -- the host -- contains the
  // hint "auth", so the hints below redacted it. classify_header decides the
  // same case in the same order for the same reason.
  if (lowered.startsWith(':')) return false;
  if (SECRET_HEADERS.has(lowered)) return true;
  return SECRET_HEADER_HINTS.some((hint) => lowered.includes(hint));
}};

// An `a=b&c=d` run with every credential-named value replaced.
//
// Rebuilt by hand rather than through `URLSearchParams.set` + `toString()`:
// that round-trip re-encodes every param, not just the touched one -- it
// collapses a repeated key to one, turns a literal space into `+`, and
// percent-encodes the marker itself, so grepping stored evidence for the same
// «redacted» every other redaction path writes finds nothing on a URL.
// Splicing leaves every untouched byte -- encoding, order, duplicates --
// exactly as the operator's browser sent it, and writes the marker as the
// same literal characters the body and header paths do. `split('&')` then
// `join('&')` is lossless, so a run with nothing to redact comes back
// byte-identical.
const redactPairs = (raw) => {{
  const pairs = raw.split('&');
  const names = pairs.map((pair) => {{
    const eq = pair.indexOf('=');
    const rawKey = eq === -1 ? pair : pair.slice(0, eq);
    try {{
      return decodeURIComponent(rawKey.replace(/\\+/g, ' ')).toLowerCase();
    }} catch {{
      return rawKey.toLowerCase();
    }}
  }});
  const oauth = names.some((name) => OAUTH_COMPANIONS.has(name));
  return pairs
    .map((pair, index) => {{
      if (!pair) return pair;
      const eq = pair.indexOf('=');
      const rawKey = eq === -1 ? pair : pair.slice(0, eq);
      let key = rawKey;
      try {{
        key = decodeURIComponent(rawKey.replace(/\\+/g, ' '));
      }} catch {{
        // Not decodable: judged on the raw bytes instead of failing the whole
        // rebuild over one malformed pair.
      }}
      if (!isSecretName(key) && !(oauth && names[index] === 'code')) return pair;
      return `${{rawKey}}=${{REDACTED}}`;
    }})
    .join('&');
}};

// `?token=...` and `?api_key=...` are as much a credential as the header form,
// and a URL is stored on every event there is: a page navigation, a request,
// and the frame a gesture happened in. Relative inputs are left alone rather
// than guessed at -- the service worker has no page to resolve them against.
//
// The fragment is judged by the same rule as the query: `#access_token=...`
// is exactly how an OAuth implicit flow hands a token back. The backend now
// redacts URLs too, at its own ingest boundary, because a rule that runs only
// in a browser is one a browser can be made not to run -- this copy is the
// first line, not the only one. A fragment with no `=` in it is a `#section`
// and is left alone rather than split into pairs it never had.
const redactUrl = (url) => {{
  if (typeof url !== 'string' || !url) return url;
  // Validates the shape; the rebuild below works on the original string, not
  // on what `URL` would reserialize it to.
  try {{
    void new URL(url);
  }} catch {{
    return url;
  }}
  const hashStart = url.indexOf('#');
  const head = hashStart === -1 ? url : url.slice(0, hashStart);
  const fragment = hashStart === -1 ? '' : url.slice(hashStart + 1);
  const queryStart = head.indexOf('?');
  const redacted =
    queryStart === -1
      ? head
      : head.slice(0, queryStart + 1) + redactPairs(head.slice(queryStart + 1));
  // The shape pass runs over the whole rebuilt URL, not only the query: a
  // token can sit in a path segment, where no parameter name exists to judge
  // it by. It substitutes rather than replaces, so a URL with no credential in
  // it comes back byte-identical -- the property the hand-splicing above
  // exists to keep.
  return redactShapes(
    hashStart === -1
      ? redacted
      : `${{redacted}}#${{fragment.includes('=') ? redactPairs(fragment) : fragment}}`,
  );
}};
"""


def _indent(source: str) -> str:
    return "".join(f"  {line}" if line.strip() else line for line in source.splitlines(True))


def sensitivity_source() -> str:
    return (
        _HEADER.format(source="sensitivity.py")
        + _PURPOSE
        + "//\n// Isolated-world half: content scripts cannot be modules, so this "
        + "publishes\n// onto the isolated world's window instead of exporting.\n"
        + "(() => {\n"
        + _indent(_rules())
        + "\n  window.__sroIsSecretName = isSecretName;\n"
        + "  window.__sroIsSecretHeader = isSecretHeader;\n"
        + "  window.__sroRedactUrl = redactUrl;\n"
        + "  window.__sroRedactShapes = redactShapes;\n"
        + "  window.__sroShapesIn = shapesIn;\n"
        + "})();\n"
    )


def sensitivity_module_source() -> str:
    return (
        _HEADER.format(source="sensitivity.py")
        + _PURPOSE
        + "//\n// Service-worker half: a module, because that worker has no window and "
        + "no\n// content script runs for a webNavigation event.\n\n"
        + _rules()
        + "\nexport { isSecretName, isSecretHeader, redactUrl, redactShapes, shapesIn };\n"
    )


def shape_source() -> str:
    return (
        _HEADER.format(source="generate_extension_recorder.py")
        + """// The reference is new_agent_arch/src/rig/shape.py:target_identity. Both are
// tested against ../../fixtures/shape-identity.json.
//
// `name` and `text` are prose -- what a person can read on the screen, and so
// what a page can render a credential into. By the time the Python rule sees
// them, wire.Target has already run redact_shapes over exactly those two
// fields. The browser reads the raw target, so the guard has to live in this
// shared function too: without it a control labelled with a bearer token keys
// as `button|«redacted»` in the rig and `button|Bearer ey...` here, and the
// same job stops matching itself across the two sides.
//
// `itemId` and `query` are deliberately NOT redacted, on either side. They are
// identifiers rather than prose, and a substitution there would move the shape
// key of every job that touches the control.

import { redactShapes } from "../content/sensitivity.module.js";

/** What to call the control this gesture touched, stably across occurrences. */
export function targetIdentity(target, kind) {
  if (!target) return `anon|${kind}`;
  const component = target.component;
  if (component) {
    if (component.itemId) return component.itemId;
    if (component.query) return component.query;
  }
  const name = target.name && redactShapes(target.name);
  const text = target.text && redactShapes(target.text);
  // Only short one-line free text names a control; a paragraph names a page.
  // The same rule, and the same forty, as identity.py's K_TEXT_IDENTITY_MAX --
  // applied to the accessible NAME as well as the innerText, because a name is
  // free text off the page too. Chrome's accessible name for the body of a
  // mail is the whole mail, and a shape keyed on the words of one mail cannot
  // match the next.
  //
  // `[...value].length`: code points, as Python's `len` counts -- a label that
  // ends in an emoji is one character on both sides, not two here.
  const namesAControl = (value) => [...value].length <= 40 && !value.includes("\\n");
  if (target.role && name && namesAControl(name)) return `${target.role}|${name}`;
  if (name && namesAControl(name)) return `name|${name}`;
  if (target.testId) return `test|${target.testId}`;
  if (text && namesAControl(text)) return `text|${text}`;
  return `anon|${kind}`;
}

/** One entry of a shape: which screen, which control, touched how. */
export function tripleOf({ system, target, kind }) {
  return [system || "", targetIdentity(target, kind), kind];
}

// The reference is backend identity.py:screen_of, the first entry of every
// triple the backend serves. Both are tested against
// ../../fixtures/screen-of.json.
//
// Scheme, host and path, without the query and without a trailing slash, and
// the fragment's route: Blue Yonder routes on the fragment, so without it every
// config screen is `/portal` and one job's gestures are every job's. The route
// is the fragment's dotted segments -- the trailing `////` are empty
// positional slots, and a `key=value` segment is an OAuth callback's pairs,
// never a route, however many dots its token has. "" for anything that is not
// a url.

/** The screen a url is on, as the backend keys a job's steps. */
export function screenOf(url) {
  try {
    const parsed = new URL(url);
    const where = `${parsed.protocol}//${parsed.host}${parsed.pathname}`
      .replace(/\\/+$/, "")
      .toLowerCase();
    const route = parsed.hash
      .slice(1)
      .split("/")
      .filter((part) => part.includes(".") && !part.includes("="))
      .join("/")
      .toLowerCase();
    return route ? `${where}#${route}` : where;
  } catch {
    return "";
  }
}
"""
    )


def page_code_source() -> str:
    source = PAGE_CODE_OUT.read_text(encoding="utf-8")
    rule = _indent(_indent(_name_rule() + _entry_rule())).replace("'", '"')
    region = (
        f"    // BEGIN generated secret-name rule\n{rule}    // END generated secret-name rule\n"
    )
    written, found = _NAME_RULE_REGION.subn(lambda _: region, source)
    if found != 1:
        raise RuntimeError("page-code.js has no one place for the secret-name rule")
    return written


def main() -> None:
    # page-code.js first: the recorder embeds its readers block.
    page_code = page_code_source()
    PAGE_CODE_OUT.write_text(page_code, encoding="utf-8")
    written = (
        (RECORDER_OUT, recorder_source()),
        (SENSITIVITY_OUT, sensitivity_source()),
        (SENSITIVITY_MODULE_OUT, sensitivity_module_source()),
        (SHAPE_OUT, shape_source()),
    )
    for path, source in written:
        path.write_text(source, encoding="utf-8")
        print(f"wrote {path}")  # noqa: T201


if __name__ == "__main__":
    main()
