"""Writes the extension's generated content scripts, secrets already baked in.

MV3 content scripts are static files -- there is no injection-time hook the
way Steel's Playwright adapter has (`add_init_script`, substituting
`__SECRET_WORDS__` fresh on every page). This runs the exact same
substitution once, from the exact same `_recorder_script()`, so
`SECRET_TOKENS` stays the one list either side reads from -- never a second
copy hand-kept under `new-chrome-extension/` that drifts from this one.

Two files come out, because the extension needs the same knowledge in two
different JavaScript realms:

`recorder.generated.js` runs in the page's own realm, where the application's
framework globals live -- an ExtJS control cannot be identified from an
isolated world, because `window.Ext` there is the isolated world's window.

`sensitivity.generated.js` runs in the isolated realm, where the network
relay redacts bodies and headers before they reach the service worker. It
carries the classification rules rather than the recorder, so the page never
sees them and the isolated world never needs the recorder.

`sensitivity.module.js` is that same knowledge a second time, as an ES module,
because the service worker has to redact as well: a `webNavigation` URL never
passes through a content script, so the isolated world's copy cannot see it. A
content script registered through `chrome.scripting` cannot be a module, and a
module service worker has no `window` to hang an IIFE's result on, so the one
list has to come out in both shapes. Both are written from the same rules
below, so neither can drift from the other or from Python.

Run with `make gen-recorder`. `test_generated_scripts_are_current.py` fails
the build when either file drifts from its source, so a forgotten regenerate
cannot ship a stale credential list.
"""

from __future__ import annotations

import json
from pathlib import Path

from sro.domain.recording.sensitivity import (
    _AUTH_HEADERS,
    _CSRF_HEADERS,
    _CSRF_HINTS,
    _SESSION_COOKIE_HINTS,
    OAUTH_COMPANIONS,
    SECRET_SHAPES,
    SECRET_SHAPES_ANY_CASE,
    SECRET_TOKENS,
)
from sro.infrastructure.steel.capture import _recorder_script

_CONTENT = Path(__file__).resolve().parents[5] / "new-chrome-extension" / "src" / "content"
_BACKGROUND = Path(__file__).resolve().parents[5] / "new-chrome-extension" / "src" / "background"

RECORDER_OUT = _CONTENT / "recorder.generated.js"
SENSITIVITY_OUT = _CONTENT / "sensitivity.generated.js"
SENSITIVITY_MODULE_OUT = _CONTENT / "sensitivity.module.js"
SHAPE_OUT = _BACKGROUND / "shape.generated.js"

_HEADER = (
    "// GENERATED by `make gen-recorder` from backend/src/sro/infrastructure/steel/{source}.\n"
    "// Do not edit this file directly -- edit that one and regenerate.\n\n"
)


def recorder_source() -> str:
    return _HEADER.format(source="recorder.js") + _recorder_script()


_PURPOSE = """// The redaction rules: which field names and which header names name a
// credential, and what a URL looks like with the credential-named query and
// fragment values taken out.
//
// `is_replayable` on the Python side answers SEMANTIC only, so an auth, CSRF
// or session value is never sent again by an executor -- storing one would be
// pure risk with no downstream use at all. They are dropped here, at the point
// of capture, rather than filtered later.
"""


def _shape_source(shapes: tuple[tuple[str, str], ...]) -> str:
    """One alternation, as a JSON string for `new RegExp`.

    A string rather than a `/.../` literal because two of these patterns
    contain a `/` inside a character class, and hand-escaping a slash is
    exactly how the two sides stop being the same expression. JavaScript spells
    a named group `(?<name>)` where Python spells it `(?P<name>)`; that one
    character is the whole difference, and `test_the_copied_secret_shapes...`
    on the rig side re-derives these from this file to prove it.
    """
    return json.dumps("|".join(f"(?<{name}>{pattern})" for name, pattern in shapes))


def _rules() -> str:
    """The rules themselves, as plain declarations both realms can wrap."""
    words = json.dumps(sorted(SECRET_TOKENS))
    auth_headers = json.dumps(sorted(_AUTH_HEADERS | _CSRF_HEADERS))
    header_hints = json.dumps(sorted({*_CSRF_HINTS, *_SESSION_COOKIE_HINTS, "cookie"}))
    companions = json.dumps(sorted(OAUTH_COMPANIONS))
    shapes = _shape_source(SECRET_SHAPES)
    shapes_any_case = _shape_source(SECRET_SHAPES_ANY_CASE)
    return f"""const SECRET_WORDS = new Set({words});
const SECRET_HEADERS = new Set({auth_headers});
const SECRET_HEADER_HINTS = {header_hints};
// An OAuth authorization code is a credential; a warehouse `code` is not, and
// this tenant's traffic carries 138 field names ending in one. So `code` is
// matched exactly, and only beside another OAuth parameter -- which is what
// tells a callback hop from an ordinary call.
const OAUTH_COMPANIONS = new Set({companions});
const REDACTED = '\u00abredacted\u00bb';

// `([A-Z]{{2,}})([A-Z][a-z])` and not `([A-Z]+)(...)`: the wider rule splits the
// lone N off `pickNPassAutoDropLocation` and leaves `Pass` bare, blanking a real
// warehouse field. Two-or-more needs three capitals in a row before it cuts, so
// `SAMLResponse` splits into saml/response and `NPass` stays whole. Measured
// over 3,270 real field, header and query names: it changes none of them.
const wordsOf = (text) =>
  (text || '')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]{{2,}})([A-Z][a-z])/g, '$1 $2')
    .split(/[^A-Za-z]+/)
    .filter(Boolean)
    .map((word) => word.toLowerCase());

const isSecretName = (name) => {{
  const words = wordsOf(name);
  return words.some((word) => SECRET_WORDS.has(word)) || SECRET_WORDS.has(words.join(''));
}};

// What a credential LOOKS like, whatever it is called. The words above are the
// secondary signal and have to be: a field name is whoever wrote the vendor's
// API's choice, an open vocabulary guessed at forever. A JWT is a JWT in any
// field, and a warehouse dock code is never a PEM block.
//
// Measured over 47,969 distinct real values from the acme store plus
// knowledge-base/http/exchanges: every pattern here matches zero of them. The
// case-blind pair is separate because `AKIA`, `AIza` and `eyJ` are
// case-SENSITIVE prefixes that a blind match would widen over the lowercase
// identifiers this traffic is full of.
const SECRET_SHAPE = new RegExp({shapes}, 'g');
const SECRET_SHAPE_ANY_CASE = new RegExp({shapes_any_case}, 'gi');

// Every credential-shaped run replaced and every other byte left alone, so a
// string with nothing in it comes back identical -- which is what lets this
// run on a URL that must not be re-encoded.
const redactShapes = (text) =>
  typeof text === 'string' && text
    ? text.replace(SECRET_SHAPE, REDACTED).replace(SECRET_SHAPE_ANY_CASE, REDACTED)
    : text;

// Which shapes are in there, first seen first, so `redacted_fields` can say
// "this went because it looked like a JWT" rather than only that it went.
const shapesIn = (text) => {{
  if (typeof text !== 'string' || !text) return [];
  const found = [];
  for (const matcher of [SECRET_SHAPE, SECRET_SHAPE_ANY_CASE]) {{
    for (const match of text.matchAll(matcher)) {{
      for (const [name, hit] of Object.entries(match.groups || {{}})) {{
        if (hit !== undefined && !found.includes(name)) found.push(name);
      }}
    }}
  }}
  return found;
}};

const isSecretHeader = (name) => {{
  const lowered = (name || '').toLowerCase().trim();
  // An HTTP/2 pseudo-header is the request line, not a header, and never a
  // credential. Checked first because `:authority` -- the host -- contains the
  // hint "auth", so the hints below redacted it. classify_header decides the
  // same case in the same order for the same reason.
  if (lowered.startsWith(':')) return false;
  if (SECRET_HEADERS.has(lowered)) return true;
  return SECRET_HEADER_HINTS.some((hint) => lowered.includes(hint));
}};

// An `a=b&c=d` run with every credential-named value replaced.
//
// Rebuilt by hand rather than through `URLSearchParams.set` + `toString()`:
// that round-trip re-encodes every param, not just the touched one -- it
// collapses a repeated key to one, turns a literal space into `+`, and
// percent-encodes the marker itself, so grepping stored evidence for the same
// «redacted» every other redaction path writes finds nothing on a URL.
// Splicing leaves every untouched byte -- encoding, order, duplicates --
// exactly as the operator's browser sent it, and writes the marker as the
// same literal characters the body and header paths do. `split('&')` then
// `join('&')` is lossless, so a run with nothing to redact comes back
// byte-identical.
const redactPairs = (raw) => {{
  const pairs = raw.split('&');
  const names = pairs.map((pair) => {{
    const eq = pair.indexOf('=');
    const rawKey = eq === -1 ? pair : pair.slice(0, eq);
    try {{
      return decodeURIComponent(rawKey.replace(/\\+/g, ' ')).toLowerCase();
    }} catch {{
      return rawKey.toLowerCase();
    }}
  }});
  const oauth = names.some((name) => OAUTH_COMPANIONS.has(name));
  return pairs
    .map((pair, index) => {{
      if (!pair) return pair;
      const eq = pair.indexOf('=');
      const rawKey = eq === -1 ? pair : pair.slice(0, eq);
      let key = rawKey;
      try {{
        key = decodeURIComponent(rawKey.replace(/\\+/g, ' '));
      }} catch {{
        // Not decodable: judged on the raw bytes instead of failing the whole
        // rebuild over one malformed pair.
      }}
      if (!isSecretName(key) && !(oauth && names[index] === 'code')) return pair;
      return `${{rawKey}}=${{REDACTED}}`;
    }})
    .join('&');
}};

// `?token=...` and `?api_key=...` are as much a credential as the header form,
// and a URL is stored on every event there is: a page navigation, a request,
// and the frame a gesture happened in. Relative inputs are left alone rather
// than guessed at -- the service worker has no page to resolve them against.
//
// The fragment is judged by the same rule as the query: `#access_token=...`
// is exactly how an OAuth implicit flow hands a token back. The backend now
// redacts URLs too, at its own ingest boundary, because a rule that runs only
// in a browser is one a browser can be made not to run -- this copy is the
// first line, not the only one. A fragment with no `=` in it is a `#section`
// and is left alone rather than split into pairs it never had.
const redactUrl = (url) => {{
  if (typeof url !== 'string' || !url) return url;
  // Validates the shape; the rebuild below works on the original string, not
  // on what `URL` would reserialize it to.
  try {{
    void new URL(url);
  }} catch {{
    return url;
  }}
  const hashStart = url.indexOf('#');
  const head = hashStart === -1 ? url : url.slice(0, hashStart);
  const fragment = hashStart === -1 ? '' : url.slice(hashStart + 1);
  const queryStart = head.indexOf('?');
  const redacted =
    queryStart === -1
      ? head
      : head.slice(0, queryStart + 1) + redactPairs(head.slice(queryStart + 1));
  // The shape pass runs over the whole rebuilt URL, not only the query: a
  // token can sit in a path segment, where no parameter name exists to judge
  // it by. It substitutes rather than replaces, so a URL with no credential in
  // it comes back byte-identical -- the property the hand-splicing above
  // exists to keep.
  return redactShapes(
    hashStart === -1
      ? redacted
      : `${{redacted}}#${{fragment.includes('=') ? redactPairs(fragment) : fragment}}`,
  );
}};
"""


def _indent(source: str) -> str:
    return "".join(f"  {line}" if line.strip() else line for line in source.splitlines(True))


def sensitivity_source() -> str:
    """The isolated world's copy: an IIFE that publishes onto that world's window.

    Generated rather than hand-written for the same reason the recorder is:
    there is one list of credential words and one list of credential headers,
    on the Python side, and a copy kept by hand under `new-chrome-extension/`
    would drift the moment somebody added a word to only one of them.
    """
    return (
        _HEADER.format(source="sensitivity.py")
        + _PURPOSE
        + "//\n// Isolated-world half: content scripts cannot be modules, so this "
        + "publishes\n// onto the isolated world's window instead of exporting.\n"
        + "(() => {\n"
        + _indent(_rules())
        + "\n  window.__sroIsSecretName = isSecretName;\n"
        + "  window.__sroIsSecretHeader = isSecretHeader;\n"
        + "  window.__sroRedactUrl = redactUrl;\n"
        + "  window.__sroRedactShapes = redactShapes;\n"
        + "  window.__sroShapesIn = shapesIn;\n"
        + "})();\n"
    )


def sensitivity_module_source() -> str:
    """The service worker's copy: the same rules as an ES module.

    The worker sees URLs no content script ever does -- `webNavigation` fires
    with no page involved -- so it cannot borrow the isolated world's copy, and
    a hand-written second list is the drift this whole file exists to prevent.
    """
    return (
        _HEADER.format(source="sensitivity.py")
        + _PURPOSE
        + "//\n// Service-worker half: a module, because that worker has no window and "
        + "no\n// content script runs for a webNavigation event.\n\n"
        + _rules()
        + "\nexport { isSecretName, isSecretHeader, redactUrl, redactShapes, shapesIn };\n"
    )


def shape_source() -> str:
    """The rig's `target_identity`, as an ES module.

    The rule is written once here as text; `new_agent_arch/src/rig/shape.py` is
    the reference and both are held to `new-chrome-extension/fixtures/
    shape-identity.json`. Emitted rather than imported for the reason the rest
    of this file is: the extension has no build step, and a hand-kept second
    copy of a matching rule drifts the moment either side is edited. Never edit
    the output; edit this.
    """
    return (
        _HEADER.format(source="generate_extension_recorder.py")
        + """// The reference is new_agent_arch/src/rig/shape.py:target_identity. Both are
// tested against ../../fixtures/shape-identity.json.
//
// `name` and `text` are prose -- what a person can read on the screen, and so
// what a page can render a credential into. By the time the Python rule sees
// them, wire.Target has already run redact_shapes over exactly those two
// fields. The browser reads the raw target, so the guard has to live in this
// shared function too: without it a control labelled with a bearer token keys
// as `button|«redacted»` in the rig and `button|Bearer ey...` here, and the
// same job stops matching itself across the two sides.
//
// `itemId` and `query` are deliberately NOT redacted, on either side. They are
// identifiers rather than prose, and a substitution there would move the shape
// key of every job that touches the control.

import { redactShapes } from "../content/sensitivity.module.js";

/** What to call the control this gesture touched, stably across occurrences. */
export function targetIdentity(target, kind) {
  if (!target) return `anon|${kind}`;
  const component = target.component;
  if (component) {
    if (component.itemId) return component.itemId;
    if (component.query) return component.query;
  }
  const name = target.name && redactShapes(target.name);
  const text = target.text && redactShapes(target.text);
  if (target.role && name) return `${target.role}|${name}`;
  if (name) return `name|${name}`;
  if (target.testId) return `test|${target.testId}`;
  // Only a short one-line text names a control; a paragraph names a page.
  // The same rule, and the same forty, as rig/shape.py's K_TEXT_IDENTITY_MAX.
  // `[...text].length`: code points, as Python's `len` counts -- a label that
  // ends in an emoji is one character on both sides, not two here.
  if (text && [...text].length <= 40 && !text.includes("\\n")) return `text|${text}`;
  return `anon|${kind}`;
}

/** One entry of a shape: which system, which control, touched how. */
export function tripleOf({ system, target, kind }) {
  return [system || "", targetIdentity(target, kind), kind];
}
"""
    )


def main() -> None:
    written = (
        (RECORDER_OUT, recorder_source()),
        (SENSITIVITY_OUT, sensitivity_source()),
        (SENSITIVITY_MODULE_OUT, sensitivity_module_source()),
        (SHAPE_OUT, shape_source()),
    )
    for path, source in written:
        path.write_text(source, encoding="utf-8")
        print(f"wrote {path}")  # noqa: T201


if __name__ == "__main__":
    main()
