"""Writes the extension's generated content scripts, secrets already baked in.

MV3 content scripts are static files -- there is no injection-time hook the
way Steel's Playwright adapter has (`add_init_script`, substituting
`__SECRET_WORDS__` fresh on every page). This runs the exact same
substitution once, from the exact same `_recorder_script()`, so
`SECRET_TOKENS` stays the one list either side reads from -- never a second
copy hand-kept under `new-chrome-extension/` that drifts from this one.

Two files come out, because the extension needs the same knowledge in two
different JavaScript realms:

`recorder.generated.js` runs in the page's own realm, where the application's
framework globals live -- an ExtJS control cannot be identified from an
isolated world, because `window.Ext` there is the isolated world's window.

`sensitivity.generated.js` runs in the isolated realm, where the network
relay redacts bodies and headers before they reach the service worker. It
carries the classification rules rather than the recorder, so the page never
sees them and the isolated world never needs the recorder.

`sensitivity.module.js` is that same knowledge a second time, as an ES module,
because the service worker has to redact as well: a `webNavigation` URL never
passes through a content script, so the isolated world's copy cannot see it. A
content script registered through `chrome.scripting` cannot be a module, and a
module service worker has no `window` to hang an IIFE's result on, so the one
list has to come out in both shapes. Both are written from the same rules
below, so neither can drift from the other or from Python.

Run with `make gen-recorder`. `test_generated_scripts_are_current.py` fails
the build when either file drifts from its source, so a forgotten regenerate
cannot ship a stale credential list.
"""

from __future__ import annotations

import json
from pathlib import Path

from sro.domain.recording.sensitivity import (
    _AUTH_HEADERS,
    _CSRF_HEADERS,
    _CSRF_HINTS,
    _SESSION_COOKIE_HINTS,
    SECRET_TOKENS,
)
from sro.infrastructure.steel.capture import _recorder_script

_CONTENT = Path(__file__).resolve().parents[5] / "new-chrome-extension" / "src" / "content"

RECORDER_OUT = _CONTENT / "recorder.generated.js"
SENSITIVITY_OUT = _CONTENT / "sensitivity.generated.js"
SENSITIVITY_MODULE_OUT = _CONTENT / "sensitivity.module.js"

_HEADER = (
    "// GENERATED by `make gen-recorder` from backend/src/sro/infrastructure/steel/{source}.\n"
    "// Do not edit this file directly -- edit that one and regenerate.\n\n"
)


def recorder_source() -> str:
    return _HEADER.format(source="recorder.js") + _recorder_script()


_PURPOSE = """// The redaction rules: which field names and which header names name a
// credential, and what a URL looks like with the credential-named query and
// fragment values taken out.
//
// `is_replayable` on the Python side answers SEMANTIC only, so an auth, CSRF
// or session value is never sent again by an executor -- storing one would be
// pure risk with no downstream use at all. They are dropped here, at the point
// of capture, rather than filtered later.
"""


def _rules() -> str:
    """The rules themselves, as plain declarations both realms can wrap."""
    words = json.dumps(sorted(SECRET_TOKENS))
    auth_headers = json.dumps(sorted(_AUTH_HEADERS | _CSRF_HEADERS))
    header_hints = json.dumps(sorted({*_CSRF_HINTS, *_SESSION_COOKIE_HINTS, "cookie"}))
    return f"""const SECRET_WORDS = new Set({words});
const SECRET_HEADERS = new Set({auth_headers});
const SECRET_HEADER_HINTS = {header_hints};
const REDACTED = '\u00abredacted\u00bb';

const wordsOf = (text) =>
  (text || '')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z]+/)
    .filter(Boolean)
    .map((word) => word.toLowerCase());

const isSecretName = (name) => {{
  const words = wordsOf(name);
  return words.some((word) => SECRET_WORDS.has(word)) || SECRET_WORDS.has(words.join(''));
}};

const isSecretHeader = (name) => {{
  const lowered = (name || '').toLowerCase().trim();
  if (SECRET_HEADERS.has(lowered)) return true;
  return SECRET_HEADER_HINTS.some((hint) => lowered.includes(hint));
}};

// An `a=b&c=d` run with every credential-named value replaced.
//
// Rebuilt by hand rather than through `URLSearchParams.set` + `toString()`:
// that round-trip re-encodes every param, not just the touched one -- it
// collapses a repeated key to one, turns a literal space into `+`, and
// percent-encodes the marker itself, so grepping stored evidence for the same
// «redacted» every other redaction path writes finds nothing on a URL.
// Splicing leaves every untouched byte -- encoding, order, duplicates --
// exactly as the operator's browser sent it, and writes the marker as the
// same literal characters the body and header paths do. `split('&')` then
// `join('&')` is lossless, so a run with nothing to redact comes back
// byte-identical.
const redactPairs = (raw) =>
  raw
    .split('&')
    .map((pair) => {{
      if (!pair) return pair;
      const eq = pair.indexOf('=');
      const rawKey = eq === -1 ? pair : pair.slice(0, eq);
      let key = rawKey;
      try {{
        key = decodeURIComponent(rawKey.replace(/\\+/g, ' '));
      }} catch {{
        // Not decodable: judged on the raw bytes instead of failing the whole
        // rebuild over one malformed pair.
      }}
      if (!isSecretName(key)) return pair;
      return `${{rawKey}}=${{REDACTED}}`;
    }})
    .join('&');

// `?token=...` and `?api_key=...` are as much a credential as the header form,
// and a URL is stored on every event there is: a page navigation, a request,
// and the frame a gesture happened in. Relative inputs are left alone rather
// than guessed at -- the service worker has no page to resolve them against.
//
// The fragment is judged by the same rule as the query: `#access_token=...`
// is exactly how an OAuth implicit flow hands a token back, and the backend
// redacts bodies and headers but never URLs -- so if this does not do it,
// nothing does. A fragment with no `=` in it is an ordinary `#section` anchor
// and is left alone rather than split into pairs it never had.
const redactUrl = (url) => {{
  if (typeof url !== 'string' || !url) return url;
  // Validates the shape; the rebuild below works on the original string, not
  // on what `URL` would reserialize it to.
  try {{
    void new URL(url);
  }} catch {{
    return url;
  }}
  const hashStart = url.indexOf('#');
  const head = hashStart === -1 ? url : url.slice(0, hashStart);
  const fragment = hashStart === -1 ? '' : url.slice(hashStart + 1);
  const queryStart = head.indexOf('?');
  const redacted =
    queryStart === -1
      ? head
      : head.slice(0, queryStart + 1) + redactPairs(head.slice(queryStart + 1));
  return hashStart === -1
    ? redacted
    : `${{redacted}}#${{fragment.includes('=') ? redactPairs(fragment) : fragment}}`;
}};
"""


def _indent(source: str) -> str:
    return "".join(f"  {line}" if line.strip() else line for line in source.splitlines(True))


def sensitivity_source() -> str:
    """The isolated world's copy: an IIFE that publishes onto that world's window.

    Generated rather than hand-written for the same reason the recorder is:
    there is one list of credential words and one list of credential headers,
    on the Python side, and a copy kept by hand under `new-chrome-extension/`
    would drift the moment somebody added a word to only one of them.
    """
    return (
        _HEADER.format(source="sensitivity.py")
        + _PURPOSE
        + "//\n// Isolated-world half: content scripts cannot be modules, so this "
        + "publishes\n// onto the isolated world's window instead of exporting.\n"
        + "(() => {\n"
        + _indent(_rules())
        + "\n  window.__sroIsSecretName = isSecretName;\n"
        + "  window.__sroIsSecretHeader = isSecretHeader;\n"
        + "  window.__sroRedactUrl = redactUrl;\n"
        + "})();\n"
    )


def sensitivity_module_source() -> str:
    """The service worker's copy: the same rules as an ES module.

    The worker sees URLs no content script ever does -- `webNavigation` fires
    with no page involved -- so it cannot borrow the isolated world's copy, and
    a hand-written second list is the drift this whole file exists to prevent.
    """
    return (
        _HEADER.format(source="sensitivity.py")
        + _PURPOSE
        + "//\n// Service-worker half: a module, because that worker has no window and "
        + "no\n// content script runs for a webNavigation event.\n\n"
        + _rules()
        + "\nexport { isSecretName, isSecretHeader, redactUrl };\n"
    )


def main() -> None:
    written = (
        (RECORDER_OUT, recorder_source()),
        (SENSITIVITY_OUT, sensitivity_source()),
        (SENSITIVITY_MODULE_OUT, sensitivity_module_source()),
    )
    for path, source in written:
        path.write_text(source, encoding="utf-8")
        print(f"wrote {path}")  # noqa: T201


if __name__ == "__main__":
    main()
